---
title: "prediction_final"
output: html_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load librarys-----------------------------------------------------------------
library(igraph)
library(data.table)
library(ggplot2)
library(tibble)
library(dplyr)
```

```{r}
# Load data---------------------------------------------------------------------
df.football.transfer <- read.csv(file = '../data/football-transfers.csv')
```

```{r }
# Optional if you want to filter something

#df.football.transfer <- df.football.transfer %>% filter(season >= 2018 &
#                                                          season <= 2021)

```

```{r }

# Create the performance column as described earlier
df.football.transfer$performance <- with(df.football.transfer, 
                                ifelse(fee == 0, market_value / (1 * age), 
                                       market_value / fee / age))

# compute the mean and standard deviation of the performance column
mean.performance <- mean(df.football.transfer$performance)
sd.performance <- sd(df.football.transfer$performance)

# create a normalized column
df.football.transfer$normalized_performance <- (
  df.football.transfer$performance - mean.performance) / sd.performance

# compute the min and max of the performance column
min.performance <- min(df.football.transfer$performance)
max.performance <- max(df.football.transfer$performance)

# create a normalized column
df.football.transfer$normalized_performance <- 
  (df.football.transfer$performance - min.performance) / (max.performance - 
                                                            min.performance)

# drop the original performance and normalized column column
df.football.transfer$performance <- NULL

df.football.transfer

dt.filtered.data <- data.table(df.football.transfer)

```

```{r }
# Max!! plus 
# Filter for top performers
 df.performers <- head(df.football.transfer[order(
   -df.football.transfer$normalized_performance), ], 50)

# Create a new dataframe with only the relevant columns
 df.remove.col <- subset(df.performers, select=c("season", "country","club",
                                                 "dealing_club", "name", "age",
                                                 "position", "nationality",
                                                 "normalized_performance"))
 
# reset the row names/index
rownames(df.remove.col) <- NULL

df.remove.col
```

```{r }

# Plot the best normalized_performance transfers of a favorite club

favorite <- "Eintracht Frankfurt"


# Filter for top performers based on age and performance score, and keep only top 20
df.performers <- df.football.transfer[df.football.transfer$club == favorite, ]
df.performers <- df.performers[order(-df.performers$normalized_performance), ][1:7, ]

# Create a new dataframe with only the relevant columns
df.performers <- subset(df.performers, select=c("dealing_club", "club", "name"))

# Create the graph
g.perform <- graph_from_data_frame(df.performers, directed = TRUE)

# Plot the graph
plot(g.perform,
     edge.arrow.size=0.5,
     vertex.size=4,
     vertex.color="lightblue",
     vertex.label.color="black",
     vertex.label.cex=0.8,
     vertex.label.dist=1.8,
     edge.label = E(g.perform)$name,
     layout=layout_with_fr)

```

```{r }

# Predictions
# Choose club ------------------------------------------------------------------
club.select <- "Bayern Munich"

# Filter the rows to include only last five seasons ----------------------------
df.football.5yrs <- subset(df.football.transfer, season >= 2017 & season <= 2021)

# Keep only the relevant columns -----------------------------------------------
df.football.5yrs <- subset(df.football.5yrs, 
                           select = c("dealing_club", "club", "name"))

# Create directed graph --------------------------------------------------------
g.football.5yrs <- graph_from_data_frame(df.football.transfer[, 
                                                              c("dealing_club",
                                                                "club")], 
                                         directed = TRUE)

# Get predicted edges ----------------------------------------------------------
m.predicted.edges <- as.matrix(cocitation(g.football.5yrs) * 
                                 (1 - get.adjacency(g.football.5yrs)))

df.predicted.edges <- as.data.frame(which(m.predicted.edges > 0, 
                                           arr.ind = TRUE))

colnames(df.predicted.edges) <- c("dealing_club", "club")

df.predicted.edges$transfer_weight <- m.predicted.edges[m.predicted.edges > 0]

df.predicted.edges$dealing_club <- 
  rownames(m.predicted.edges)[df.predicted.edges$dealing_club]

df.predicted.edges$club <- 
  rownames(m.predicted.edges)[df.predicted.edges$club]

# Remove self-loops where dealing club and club are the same -------------------
df.predicted.edges <- subset(df.predicted.edges, dealing_club != club)

# Normalize the transfer_weight column -----------------------------------------
max.transfer.weight <- max(df.predicted.edges$transfer_weight)

df.predicted.edges$transfer_prob <- round(df.predicted.edges$transfer_weight / 
                                            max.transfer.weight, 2)

# Filter edges to only include those with selected club as target --------------
df.predicted.edges <- df.predicted.edges[df.predicted.edges$club == 
                                             club.select, ]
df.predicted.edges <- df.predicted.edges[df.predicted.edges$dealing_club != 
                                             club.select, ]

# Keep only the relevant columns -----------------------------------------------
df.predicted.edges <- subset(df.predicted.edges, 
                             select=c("dealing_club", "club", "transfer_prob"))

# Remove the index column by setting row.names to NULL -------------------------
row.names(df.predicted.edges) <- NULL

# Sort edges by transfer probability -------------------------------------------
df.predicted.edges <- df.predicted.edges[order(df.predicted.edges$transfer_prob, 
                                                 decreasing = TRUE), ]
df.top.5.pred.dealing.clubs <- df.predicted.edges[1:5, ]
rownames(df.top.5.pred.dealing.clubs) <- NULL

# Add a new column containing the importance in the list
df.top.5.pred.dealing.clubs <- df.top.5.pred.dealing.clubs %>% 
  mutate(importance = row_number())
df.top.5.pred.dealing.clubs <- 
  df.top.5.pred.dealing.clubs[c("importance", 
                                names(df.top.5.pred.dealing.clubs)
                                [-which(names(df.top.5.pred.dealing.clubs) == 
                                          "importance")])]



# Print the top 5 predicted transfers ------------------------------------------
cat("Top 5 predicted transfers for", club.select, ":\n")
print(df.top.5.pred.dealing.clubs)

```

```{r }
# Choose club ------------------------------------------------------------------
club.select <- "Bayern Munich"

# Create directed graph from df.top.5.pred.dealing.clubs
g.test <- graph_from_data_frame(df.top.5.pred.dealing.clubs[, 
                                                       c("dealing_club",
                                                         "club", "transfer_prob")],
                           directed = TRUE)

# Set edge weights to transfer_probability
E(g.test)$weight <- df.top.5.pred.dealing.clubs$transfer_prob

# Set vertex colors for chosen club and dealing clubs
V(g.test)$color <- ifelse(V(g.test)$name == club.select, "red", "blue")

# Set edge color palette
edge.colors <- colorRampPalette(c("yellow", "red"))(100)

# Plot graph
plot(g.test, 
     vertex.size = 10, 
     vertex.label.color = "black", 
     vertex.label.cex = 0.8, 
     vertex.color = V(g.test)$color, 
     vertex.frame.color = "gray", 
     edge.arrow.size = E(g.test)$weight*5, 
     edge.width = E(g.test)$weight*25,
     edge.label = round(E(g.test)$weight, digits = 2),
     edge.color = edge.colors[cut(E(g.test)$weight, breaks = 100)])
     
```

```{r }
# BACK-UP --> Better to show the graph above

# Create directed graph from df.top.5.pred.dealing.clubs
g.test <- graph_from_data_frame(df.top.5.pred.dealing.clubs[, 
                                                       c("dealing_club",
                                                         "club", "transfer_prob")],
                           directed = TRUE)

# Set edge weights to transfer_probability
E(g.test)$weight <- df.top.5.pred.dealing.clubs$transfer_prob
E(g.test)$weight[E(g.test)$weight <= 0] <- NA


# Set vertex colors for chosen club and dealing clubs
V(g.test)$color <- ifelse(V(g.test)$name == club.select, "red", "blue")

# Plot graph
plot(g.test, 
     vertex.size = 10, 
     vertex.label.color = "black", 
     vertex.label.cex = 0.8, 
     vertex.color = V(g.test)$color, 
     vertex.frame.color = "gray", 
     edge.arrow.size = 0.5, 
     edge.color = "gray", 
     edge.width = E(g.test)$weight*10,
     edge.label = round(E(g.test)$weight, digits = 2))
```