---
title: "Shiny_directed_graph"
output: html_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the Required Libraries---------------------------------------------------
library(shiny)
library(dplyr)
library(ggplot2)
library(igraph)
library(visNetwork)


```

```{r}
#Load the Data
df.football.transfer <- read.csv(file = '../data/football-transfers.csv')

#df.football.transfer <- df.football.transfer %>% filter(season >= 2020 &
#                                                          season <= 2021)

data <- df.football.transfer



```


```{r}
# FINISHED

# Page directed graph analysis performance index

ui <- fluidPage(
  titlePanel("Football Transfers Network Exploration by self-developed performance index "),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui"),
      selectInput("position", "Position:", c("All", unique(data$position_category)))
      ),
    
    mainPanel(
      tags$h4("Top 10 transfers to chosen club by normalized performance index", 
              style = "font-weight: bold; font-size: 24px; text-align: center"),
      fluidRow( 
        column(6, visNetworkOutput("performers_graph")),
        column(6, plotOutput("scatter_plot"))
      ),
      tags$h4("Detailed informations about the transfers displayed above",
              style = "font-weight: bold; font-size: 24px; text-align: center"),
      dataTableOutput("performers_table")
    )
  )
)

server <- function(input, output) {
  season.data <- reactive({
    data %>%
      filter(season >= input$year[1] & season <= input$year[2]) %>%
      filter(country == input$country) %>%
      filter(if (input$position != "All") position_category == input$position else TRUE)
  })
  
  output$club_ui <- renderUI({
    clubs.filtered <- season.data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs.filtered))
  })
  
  # Plot directed graph interactive of top performers
  df.performers <- reactive({
    season.filtered <- season.data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers.top <- season.filtered[order(-season.filtered$normalized_performance), ][1:10, ]
    
    # Create a new dataframe with only the relevant columns
    performers.df <- subset(performers.top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers.df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    df.nodes <- data.frame(id = V(g.perform)$name, label = V(g.perform)$name)
    df.edges <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2],
                           label = E(g.perform)$name)
    
    # Create a visNetwork object instead of using the base igraph plot
    visNetwork(df.nodes, df.edges, width = "100%", height = "600px") %>%
      visEdges(arrows = "to", font = list(size = 10, face = "sans-serif"), label = df.edges$label) %>%
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
      visLayout(randomSeed = 42)
  })
  
  output$performers_graph <- renderVisNetwork({
    df.performers()
  })
  
  # Create a table of detailed informations about top perfomers
  filtered.data <- reactive({
    season.filtered <- season.data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    df.performers.top <- season.filtered[order(-season.filtered$normalized_performance), ][1:10, ]
    
    # Create a new dataframe with only the relevant columns
    df.performers <- subset(df.performers.top, select=c("season", "country", "club", "dealing_club",
                                                     "name", "age", "position_category", "nationality",
                                                     "normalized_performance"))
    
    # Reset the row names/index
    rownames(df.performers) <- NULL
    df.performers
  })
  
  # Create a scatter plot of market values by position and age based on the filtered data
  output$scatter_plot <- renderPlot({
    filtered.data() %>%
      ggplot(aes(x = age, y = normalized_performance, color = position_category)) +
      geom_point(size = 2, alpha = 0.6) +
      scale_color_brewer(palette = "Set1") +
      scale_y_continuous(labels = scales::comma) +
      labs(x = "Age", y = "Normalized Performance",
           title = "Performance by Position and Age")+
      theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
            axis.title = element_text(face = "bold"),
            legend.title = element_text(face = "bold"),
            legend.text = element_text(face = "bold"))
  })
  output$performers_table <- renderDataTable({
    filtered.data() 
    },
    options = list(
    searching = FALSE,
    lengthChange = FALSE,
    paging = FALSE,
    pageLength = 10
))
}
```

```{r}

#load the app 
shinyApp(ui, server)
```


```{r}
# FINISHED!! --> Filter built- in beschreiben als nur für highlighten oder bekomme ich den filter noch hin
# siehe code unten lässt sich nur nicht kombinieren
# Zeitraum 1 jahr vllt ein anderer Filter sosnt dauert das laden viel zu lange
# Page directed graph
# Shiny app UI
ui <- fluidPage(
  titlePanel("Overview about the football Transfers Network by country"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
      sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
#      selectInput("year",
#        "Select a year:",
#        choices = 1980:2021,
#        selected = 1980, width = "100%"),
      selectInput("country", "Country:", unique(data$country)),
      selectInput("position", "Position:", c("All", unique(data$position_category)))
    ),
    
    mainPanel(
      visNetworkOutput("directed_graph"),
      verbatimTextOutput("graph_summary"),
      verbatimTextOutput("graph_measures"),
      dataTableOutput("centrality_table"),
      plotOutput("degree_distribution"),
      fluidRow(
        column(6, dataTableOutput("in_degree_table")),
        column(6, dataTableOutput("out_degree_table"))
      )
  )
)
)


# Shiny app server
server <- function(input, output) {
  selected.club <- reactiveVal()
  graph_selected_club <- reactiveVal()

  
  season.data <- reactive({
    data %>%
      filter(season >= input$year[1] & season <= input$year[2]) %>%
      filter(country == input$country) %>%
      filter(if (input$position != "All") position_category == input$position else TRUE)
  })


  # Create the directed graph
  directed.graph <- reactive({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    df.nodes <- data.frame(id = V(g.directed)$name, label = V(g.directed)$name)
    df.edges <- data.frame(from = get.edgelist(g.directed)[, 1], to = get.edgelist(g.directed)[, 2],
                           label = E(g.directed)$name)
    
  visNetwork(df.nodes, df.edges, width = "100%", height = "600px") %>%
    visEdges(arrows = "to", font = list(size = 10, face = "sans-serif"), label = df.edges$label) %>%
    visNodes(
      color = list(
        highlight = list(
          background = "red",
          border = "red"
        )
      )
    ) %>%
    visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
    visEvents(select = "function(properties) { Shiny.setInputValue('selectedClub', properties.nodes[0]); }") %>%
    visEvents(deselectNode = 
                "function() { Shiny.setInputValue('directed_graph_unselected', true, {priority: 'event'}); }")
  })


  # Observe the selected club from the directed_graph and update the selected_club reactive variable
  observeEvent(input$selectedClub, {
    selected.club(input$selectedClub)
  })
  
  # Observe the selected club from the directed_graph and update the selected_club reactive variable
  observeEvent(input$selectedClub, {
  graph_selected_club(input$selectedClub)
  })
  
  # Observe the deselected club from the directed_graph and reset the selected_club reactive variable
  observeEvent(input$directed_graph_unselected, {
    selected.club(NULL)
  })
  
  # Observe the deselected club from the directed_graph and reset the selected_club reactive variable
  observeEvent(input$directed_graph_unselected, {
  graph_selected_club(NULL)
  })
    
  # Render the directed graph
  output$directed_graph <- renderVisNetwork({
    directed.graph()
  })

  # Render the number of nodes and edges
  output$graph_summary <- renderText({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    num_nodes <- gorder(g.directed)
    num_edges <- gsize(g.directed)
    paste("Number of nodes:", num_nodes, "\nNumber of edges:", num_edges)
})
  # Calculate centrality measures for the filtered graph
  centrality.measures <- reactive({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    degree.centrality <- degree(g.directed, mode = "all")
    closeness <- closeness(g.directed)
    betweenness <- round(betweenness(g.directed), 4)
    eigenvector <- round(evcent(g.directed)$vector, 4)
    pr <- page_rank(g.directed)$vector
    pr_norm <- scale(pr)

    # Normalized centrality measures for better interpretations---------------------
    normalized.degree <- round(degree(g.directed, normalized = TRUE), 4)
    normalized.closeness <- round(closeness(g.directed, normalize = TRUE), 4)
    normalized.betweenness <- round(betweenness(g.directed, normalize = TRUE), 4)
    normalized.pr <- round(scale(pr,center = min(pr), 
                             scale = max(pr) - min(pr)),4)

    # Create a dataframe with centrality measures
    club_names <- V(g.directed)$name

    df.centrality.measures_clubs <- data.frame(
      club_name = club_names,
      degree = degree.centrality,
      normalized_degree = normalized.degree,
      normalized_closeness = normalized.closeness,
      normalized_betweenness = normalized.betweenness,
      eigenvector = eigenvector,
      normalized_pagerank = normalized.pr
    )

    return(df.centrality.measures_clubs)
  })

  # Render the centrality measures table
  output$centrality_table <- renderDataTable({
    df.centrality <- centrality.measures()
    
    if (!is.null(selected.club()) && selected.club() != "") {
      df.centrality <- df.centrality %>% filter(club_name == selected.club())
    }
    df.centrality
  }, options = list(searching = FALSE))
    
  # Render the degree distribution histogram
  output$degree_distribution <- renderPlot({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    degree.subgraph <- degree(g.directed)
    hist(degree.subgraph,
         main = paste("Degree Distribution of ", input$country),
         xlab = "Degree", ylab = "Number of clubs", col = "blue", border = "white")
  })

  # Render the statistical measures
  output$graph_measures <- renderText({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    avg.degree <- mean(degree(g.directed))
    clustering.coeff <- transitivity(g.directed, type = "average")
    avg.path.length <- average.path.length(g.directed)

    paste("Statistical summary of the transfer network of", input$country, ":",
          "\nAvg. degree of the directed graph:", round(avg.degree,4),
          "\nClustering coefficient of the directed graph:", round(clustering.coeff,4),
          "\nAvg. path length of the directed graph:", round(avg.path.length,4))
  })
  
  # Render the in-degree table
  output$in_degree_table <- renderDataTable({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    in.degree <- data.frame(club = V(g.directed)$name, in.degree = degree(g.directed, mode = "in"))
    
    if (!is.null(selected.club()) && selected.club() != "") {
      in.degree <- in.degree %>% filter(club == selected.club())
    }
    
    in.degree
  }, options = list(searching = FALSE))
  
  # Render the out-degree table
  output$out_degree_table <- renderDataTable({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    out.degree <- data.frame(club = V(g.directed)$name, out.degree = degree(g.directed, mode = "out"))
    
    if (!is.null(selected.club()) && selected.club() != "") {
      out.degree <- out.degree %>% filter(club == selected.club())
    }
    
    out.degree
  }, options = list(searching = FALSE))
}

```

```{r}

#load the app 
shinyApp(ui, server)
```



```{r}
# Backup!!!!!!!!!
# Shiny app UI Built in function is working but not clicking on nodes
ui <- fluidPage(
  titlePanel("Overview about the football Transfers Network"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
      sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      selectInput("position", "Position:", c("All", unique(data$position_category)))
    ),
    
    mainPanel(
      visNetworkOutput("directed_graph"),
      verbatimTextOutput("graph_summary"),
      verbatimTextOutput("graph_measures"),
      dataTableOutput("centrality_table"),
      plotOutput("degree_distribution")
  )
)
)


# Shiny app server
server <- function(input, output) {
  selected.club <- reactiveVal()
  graph_selected_club <- reactiveVal()

  
  season.data <- reactive({
    data %>%
      filter(season >= input$year[1] & season <= input$year[2]) %>%
      filter(country == input$country) %>%
      filter(if (input$position != "All") position_category == input$position else TRUE)
  })


  # Create the directed graph
  directed.graph <- reactive({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    df.nodes <- data.frame(id = V(g.directed)$name, label = V(g.directed)$name)
    df.edges <- data.frame(from = get.edgelist(g.directed)[, 1], to = get.edgelist(g.directed)[, 2],
                           label = E(g.directed)$name)
    
    visNetwork(df.nodes, df.edges, width = "100%", height = "600px") %>%
      visEdges(arrows = "to", font = list(size = 10, face = "sans-serif"), label = df.edges$label) %>%
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
      visEvents(select = "function(properties) { Shiny.setInputValue('selectedClub', properties.nodes[0]); }") %>%
      visEvents(deselectNode = 
                  "function() { Shiny.setInputValue('directed_graph_unselected', true, {priority: 'event'}); }")
  })


  # Observe the selected club from the directed_graph and update the selected_club reactive variable
  observeEvent(input$selectedClub, {
    selected.club(input$selectedClub)
  })
  
  # Observe the selected club from the directed_graph and update the selected_club reactive variable
  observeEvent(input$selectedClub, {
  graph_selected_club(input$selectedClub)
  })
  
  # Observe the deselected club from the directed_graph and reset the selected_club reactive variable
  observeEvent(input$directed_graph_unselected, {
    selected.club(NULL)
  })
  
  # Observe the deselected club from the directed_graph and reset the selected_club reactive variable
  observeEvent(input$directed_graph_unselected, {
  graph_selected_club(NULL)
  })
    
  # Render the directed graph
  output$directed_graph <- renderVisNetwork({
    directed.graph()
  })

  # Render the number of nodes and edges
  output$graph_summary <- renderText({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    num_nodes <- gorder(g.directed)
    num_edges <- gsize(g.directed)
    paste("Number of nodes:", num_nodes, "\nNumber of edges:", num_edges)
})
  # Calculate centrality measures for the filtered graph
  centrality.measures <- reactive({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    degree.centrality <- degree(g.directed, mode = "all")
    closeness <- closeness(g.directed)
    betweenness <- round(betweenness(g.directed), 4)
    eigenvector <- round(evcent(g.directed)$vector, 4)

    # Normalized centrality measures for better interpretations---------------------
    normalized.degree <- round(degree(g.directed, normalized = TRUE), 4)
    normalized.closeness <- round(closeness(g.directed, normalize = TRUE), 4)
    normalized.betweenness <- round(betweenness(g.directed, normalize = TRUE), 4)

    # Create a dataframe with centrality measures
    club_names <- V(g.directed)$name

    df.centrality.measures_clubs <- data.frame(
      club_name = club_names,
      degree = degree.centrality,
      normalized_degree = normalized.degree,
      normalized_closeness = normalized.closeness,
      normalized_betweenness = normalized.betweenness,
      eigenvector = eigenvector
    )

    return(df.centrality.measures_clubs)
  })

  # Render the centrality measures table
  output$centrality_table <- renderDataTable({
    df.centrality <- centrality.measures()
  
    # Filter player data based on the selected club
    if (!is.null(selected.club())) {
      df.centrality <- df.centrality %>% filter(club_name == selected.club())
    }
    
    # Filter player data based on the built-in filter of the interactive graph
    if (!is.null(input$directed_graph_selected)) {
      df.centrality <- df.centrality %>% filter(club_name %in% input$directed_graph_selected)
    }
  
    df.centrality
  }, options = list(searching = TRUE))
    
  # Render the degree distribution histogram
  output$degree_distribution <- renderPlot({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    degree.subgraph <- degree(g.directed)
    hist(degree.subgraph,
         main = paste("Degree Distribution of the original g.directed for", input$country),
         xlab = "Degree", ylab = "Number of clubs", col = "blue", border = "white")
  })

  # Render the statistical measures
  output$graph_measures <- renderText({
    g.directed <- graph_from_data_frame(season.data()[, c("dealing_club", "club", "name")], directed = TRUE)
    avg.degree <- mean(degree(g.directed))
    clustering.coeff <- transitivity(g.directed, type = "average")
    avg.path.length <- average.path.length(g.directed)

    paste("Statistical summary of the transfer network of", input$country, ":",
          "\nAvg. degree of the directed graph:", round(avg.degree,4),
          "\nClustering coefficient of the directed graph:", round(clustering.coeff,4),
          "\nAvg. path length of the directed graph:", round(avg.path.length,4))
  })
}
```

```{r}


# Template with Filter

ui <- fluidPage(
  titlePanel("XXX"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui"),
      selectInput("position", "Position:", c("All", unique(data$position_category)))
      ),
    
    mainPanel(
    )
  )
)

# Server side
server <- function(input, output) {
  season.data <- reactive({
    data %>%
      filter(season >= input$year[1] & season <= input$year[2]) %>%
      filter(country == input$country) %>%
      filter(if (input$position != "All") position_category == input$position else TRUE)
  })
  
  output$club_ui <- renderUI({
    clubs.filtered <- season.data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs.filtered))
  })

}
```

```{r}

#load the app 
shinyApp(ui, server)
```

```{r}
# test zooming with visNetwork is working first try without direction and player
# ui
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics by normalized performance index of the player"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club by normalized performance index of the player"),
      #verbatimTextOutput("player_count"),
      visNetworkOutput("performers_graph"),
      dataTableOutput("performers_table")
    )
  )
)

#Create the Server Function

server <- function(input, output) {
  
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  # Plot directed graph interactive of top performers
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers_df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    nodes_df <- data.frame(id = V(g.perform)$name, label = V(g.perform)$name)
    edges_df <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2])
    
    # Create a visNetwork object instead of using the base igraph plot
    visNetwork(nodes_df, edges_df, width = "100%", height = "600px") %>%
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
      visLayout(randomSeed = 42)
  })
  output$performers_graph <- renderVisNetwork({
    df.performers()
  })
  
  filtered_data <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("season", "country", "club", "dealing_club",
                                                     "name", "age", "position_category", "nationality",
                                                     "normalized_performance"))
    
    # Reset the row names/index
    rownames(performers_df) <- NULL
    performers_df
  })
  output$performers_table <- renderDataTable({
    filtered_data()
  })
  
}
```

```{r}
#load the app 
shinyApp(ui, server)
```

```{r}
# fist try
# first try
#Create the User Interface
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club"),
      #verbatimTextOutput("player_count"),
      plotOutput("performers_graph")
    )
  )
)

#Create the Server Function

server <- function(input, output) {
  
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  #test
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers_df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    nodes_df <- data.frame(id = V(g.perform)$name)
    edges_df <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2])
    
    # Plot the graph
    plot(g.perform,
         edge.arrow.size=0.5,
         vertex.size=4,
         vertex.color="lightblue",
         vertex.label.color="black",
         vertex.label.cex=0.8,
         vertex.label.dist=1.8,
         edge.label = E(g.perform)$name,
        layout=layout_with_fr)
  })
  
  output$performers_graph <- renderPlot({
    df.performers()
  })

}

```

```{r}
#load the app 
shinyApp(ui, server)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```