---
title: "Max_to_do"
output: html_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#
#to-do:
#- Filter hinzufügen wie unten beschrieben und noch position_category hinzufügen ganz unten als letzten
#- Average age und number of player --> den code ist von lily und schon im shiny format sollte somit ganz gut funktionieren
#- Wie unten beschrieben die zwei tables auf deine Seite
#- Sortieren der bars nach der größe von links nach rechts


```

```{r}
# Hier der code von Lily wegen der average age und number of player

# Load the Required Libraries
install.packages("shiny")
library(shiny)
library(dplyr)
library(ggplot2)


#Load the Data
df.football.transfer <- read.csv(file = 'data/football-transfers.csv')


#Create the User Interface
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a season and a window"),
      selectInput("season", "Season:", unique(df.football.transfer$season)),
      selectInput("window", "Window:", unique(df.football.transfer$window))
    ),
    
    mainPanel(
      h4("Descriptive Statistics"),
      verbatimTextOutput("player_count"),
      verbatimTextOutput("market_value_mean"),
      verbatimTextOutput("average_age"),
      verbatimTextOutput("average_fee")
    )
  )
)



#Create the Server Function

server <- function(input, output) {
  
  season_data <- reactive({
    df.football.transfer %>% filter(season == input$season, window == input$window)
  })
  
  output$player_count <- renderPrint({
    paste("Number of Football Players:", nrow(season_data()))
  })
  
  output$market_value_mean <- renderPrint({
    paste("Average Market Value:", mean(season_data()$market_value))
  })
  
  output$average_age <- renderPrint({
    paste("Average Age:", mean(season_data()$age))
  })
  
  output$average_fee <- renderPrint({
    paste("Average Transfer Fee:", mean(season_data()$fee))
  })
}


#load the app 
shinyApp(ui, server)
```

```{r}
# Hier einmal für dich die drei Filter wo sich auch country automatisch anpasst.
# Bitte die reihenfolge zeit --> country --> club behalten 
# Bitte noch position_category

# ui
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club by normalized performance index of the player"),
      #verbatimTextOutput("player_count"),
      visNetworkOutput("performers_graph") # Change this line
    )
  )
)

# hier sind für den Filter oben die ersten beiden Functionen noch relevant die auf 
# die sich dann im nachhinein bezogen wird
server <- function(input, output) {
  
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  #test
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
  # ...
```

```{r}
# Load data---------------------------------------------------------------------
df.football.transfer <- read.csv(file = '../data/football-transfers.csv')
dt.filtered.data <- data.table(df.football.transfer)
```

```{r}
# Bitte diese beiden tables bei dir mit aufnehmen unter descriptive

# Group by year and count the number of transfers per year----------------------
dt.filtered.data.per.year <- dt.filtered.data[, .(n_transfers = .N), 
                                       by = season][order(season)]
print(dt.filtered.data.per.year)

# Group by club and count the number of transfers-------------------------------
dt.filtered.data.per.club <- dt.filtered.data[, .(n_transfers = .N), 
                                       by = club][order(-n_transfers)]
print(dt.filtered.data.per.club)


```



```{r}

```

```{r}

```

```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```