---
title: "Shiny_directed_graph"
output: html_document
date: "2023-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the Required Libraries---------------------------------------------------
library(shiny)
library(dplyr)
library(ggplot2)
library(igraph)
library(visNetwork)


```

```{r}
#Load the Data
df.football.transfer <- read.csv(file = '../data/football-transfers.csv')

#df.football.transfer$season <- as.Date(paste0(df.football.transfer$season, "-01-01"), origin = "1970-01-01")
#df.football.transfer$season <- format(df.football.transfer$season, "%Y")
df.football.transfer <- df.football.transfer %>% filter(season >= 2018 &
                                                          season <= 2021)

#df.football.transfer$season <- as.Date(paste0(df.football.transfer$season, "-01-01"), origin = "1970-01-01")

# Create the performance column as described earlier
#df.football.transfer$performance <- with(df.football.transfer, 
#                                ifelse(fee == 0, market_value / (1 * age), 
#                                       market_value / fee / age))

# compute the mean and standard deviation of the performance column
#mean.performance <- mean(df.football.transfer$performance)
#sd.performance <- sd(df.football.transfer$performance)

# create a normalized column
#df.football.transfer$normalized_performance <- (
#  df.football.transfer$performance - mean.performance) / sd.performance

# compute the min and max of the performance column
#min.performance <- min(df.football.transfer$performance)
#max.performance <- max(df.football.transfer$performance)

# create a normalized column
#df.football.transfer$normalized_performance <- 
#  (df.football.transfer$performance - min.performance) / (max.performance - 
#                                                            min.performance)

# drop the original performance and normalized column column
#df.football.transfer$performance <- NULL

data <- df.football.transfer



```

```{r}


```
```{r}
# Test with direction and player
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club"),
      visNetworkOutput("performers_graph")
    )
  )
)

server <- function(input, output) {
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers_df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    nodes_df <- data.frame(id = V(g.perform)$name, label = V(g.perform)$name)
    edges_df <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2],
                           label = E(g.perform)$name) # Add label column here
    
    # Create a visNetwork object instead of using the base igraph plot
    visNetwork(nodes_df, edges_df, width = "100%", height = "600px") %>%
      visEdges(arrows = "to", font = list(size = 10, face = "sans-serif"), label = edges_df$label) %>% # Set label here
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
      visLayout(randomSeed = 42)
  })
  
  output$performers_graph <- renderVisNetwork({
    df.performers()
  })
}
```

```{r}
# test zooming with visNetwork is working first try without direction and player
# ui
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club by normalized performance index of the player"),
      #verbatimTextOutput("player_count"),
      visNetworkOutput("performers_graph") # Change this line
    )
  )
)

#Create the Server Function

server <- function(input, output) {
  
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  #test
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers_df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    nodes_df <- data.frame(id = V(g.perform)$name, label = V(g.perform)$name)
    edges_df <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2])
    
    # Create a visNetwork object instead of using the base igraph plot
    visNetwork(nodes_df, edges_df, width = "100%", height = "600px") %>%
      visOptions(highlightNearest = TRUE, nodesIdSelection = TRUE) %>%
      visLayout(randomSeed = 42)
  })
  
  output$performers_graph <- renderVisNetwork({
    df.performers()
  })
}
```


```{r}
# fist try
# first try
#Create the User Interface
ui <- fluidPage(
  titlePanel("Football Transfers Descriptive Statistics"),
  
  sidebarLayout(
    sidebarPanel(
      h4("Choose a country, club, duration"),
            sliderInput("year", "Select year range:",
                  min = min(data$season),
                  max = max(data$season),
                  value = c(min(data$season), max(data$season)),
                  step = 1,sep = ""),
      selectInput("country", "Country:", unique(data$country)),
      uiOutput("club_ui")
    ),
    
    mainPanel(
      h4("Transfers to chosen club"),
      #verbatimTextOutput("player_count"),
      plotOutput("performers_graph")
    )
  )
)

#Create the Server Function

server <- function(input, output) {
  
  season_data <- reactive({
    data %>% filter(season >= input$year[1] & season <= input$year[2])
  })
  
  output$club_ui <- renderUI({
    clubs_filtered <- season_data() %>% filter(country == input$country) %>% select(club)
    selectInput("club", "Club:", choices = unique(clubs_filtered))
  })
  
  #test
  df.performers <- reactive({
    season_filtered <- season_data() %>% filter(country == input$country, club == input$club)
    
    # Filter for top performers based on age and performance score, and keep only top 20
    performers_top <- season_filtered[order(-season_filtered$normalized_performance), ][1:7, ]
    
    # Create a new dataframe with only the relevant columns
    performers_df <- subset(performers_top, select=c("dealing_club", "club", "name"))
    
    # Create the graph
    g.perform <- graph_from_data_frame(performers_df, directed = TRUE)
    
    # Convert graph to edges and nodes data frames
    nodes_df <- data.frame(id = V(g.perform)$name)
    edges_df <- data.frame(from = get.edgelist(g.perform)[, 1], to = get.edgelist(g.perform)[, 2])
    
    # Plot the graph
    plot(g.perform,
         edge.arrow.size=0.5,
         vertex.size=4,
         vertex.color="lightblue",
         vertex.label.color="black",
         vertex.label.cex=0.8,
         vertex.label.dist=1.8,
         edge.label = E(g.perform)$name,
        layout=layout_with_fr)
  })
  
  output$performers_graph <- renderPlot({
    df.performers()
  })

}

```

```{r}
#load the app 
shinyApp(ui, server)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```